# -*- coding: utf-8 -*-

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJR04Md5OWu2Jw6tzWYd69wLoRGTycyK
"""

import sys,math


t = int(input())
for i in range(t):
    n, m = map(int, input().split())
    print(math.factorial(m)//(math.factorial(m-n)*math.factorial(n)))

