SELECT DATE_FORMAT(S.SALES_DATE, '%Y') YEAR , DATE_FORMAT(S.SALES_DATE, '%m') MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM USER_INFO I, ONLINE_SALE S
WHERE I.USER_ID = S.USER_ID
  AND I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, I.GENDER
ORDER BY 1, 2, 3