SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(PRICE * AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
  AND TO_CHAR(O.PRODUCE_DATE, 'YYYY-mm') = '2022-05'
GROUP BY O.PRODUCT_ID,  P.PRODUCT_NAME
ORDER BY 3 DESC, 1