WITH VALUE AS (
    SELECT H.HISTORY_ID, H.CAR_ID, 
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
        , C.CAR_TYPE
        , C.DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID

WHERE C.CAR_TYPE = '트럭')

SELECT
    VALUE.HISTORY_ID,
    ROUND((VALUE.DAILY_FEE 
    * VALUE.PERIOD 
    * (100 - IFNULL(P.DISCOUNT_RATE,0))/100),0) AS FEE
FROM VALUE
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = VALUE.CAR_TYPE
    AND P.DURATION_TYPE = VALUE.DURATION_TYPE
ORDER BY FEE DESC, VALUE.HISTORY_ID DESC