SELECT * FROM
(
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
) a
WHERE (
    SELECT COUNT(*) 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
    AND CAR_ID = a.CAR_ID
    ) >= 5
    AND RECORDS > 0
ORDER BY MONTH, CAR_ID DESC
