WITH TMP AS (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT TMP.*, FOOD_PRODUCT.PRODUCT_NAME
FROM TMP, FOOD_PRODUCT
WHERE TMP.MAX_PRICE = FOOD_PRODUCT.PRICE
  AND TMP.CATEGORY = FOOD_PRODUCT.CATEGORY
ORDER BY 2 DESC