SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO ON FP.PRODUCT_ID=FO.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) =5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC , PRODUCT_ID