SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (SELECT CAR_ID 
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE MONTH(START_DATE) BETWEEN 8 AND 10
                 GROUP BY CAR_ID
                 HAVING COUNT(*) >=5) AND MONTH(START_DATE) BETWEEN 8 and 10
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH, CAR_ID DESC;
