SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r
ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT COUNT(*) cnt, MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING cnt = (
            SELECT COUNT(*) cnt
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY cnt DESC
            LIMIT 1
        )
    ) a
)
ORDER BY REVIEW_DATE, REVIEW_TEXT
