WITH TB AS (SELECT *
            FROM USER_INFO
            WHERE YEAR(JOINED) = '2021'
    )

SELECT YEAR(SALES_DATE) YEAR
        , MONTH(SALES_DATE) MONTH
        , COUNT(DISTINCT TB.USER_ID) PUCHASED_USERS
        , ROUND((COUNT(DISTINCT TB.USER_ID)) / (SELECT COUNT(*) FROM TB), 1) PUCHASED_RATIO
FROM TB, ONLINE_SALE S
WHERE TB.USER_ID = S.USER_ID
GROUP BY 1, 2
ORDER BY 1, 2