SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR C,
     CAR_RENTAL_COMPANY_RENTAL_HISTORY H,
     CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_ID = H.CAR_ID
  AND C.CAR_TYPE = P.CAR_TYPE
  AND C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE END_DATE > '20221101'
                         AND START_DATE < '20221201')
  AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID
HAVING FEE >= 500000
   AND FEE < 2000000
   AND C.CAR_TYPE IN ('SUV', '세단')
ORDER BY FEE DESC, CAR_TYPE, C.CAR_ID