WITH MaxPriceCTE AS (
  SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
  FROM FOOD_PRODUCT
  WHERE CATEGORY IN ('과자', '식용유', '김치', '국')
  GROUP BY CATEGORY
)

SELECT FP.CATEGORY, MP.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN MaxPriceCTE MP ON FP.CATEGORY = MP.CATEGORY AND FP.PRICE = MP.MAX_PRICE
ORDER BY MAX_PRICE DESC;